#!/bin/sh
#SBATCH --job-name=finetuning_frozen_backbone_SurgicalPhaseRecognition_LessTrainingData_EndoViT
#SBATCH --outputs=./finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/test_out.txt # Standard outputs of the script (Can be absolute or relative path). %A adds the job id to the file name so you can launch the same script multiple times and get different logging files
#SBATCH --error=./finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/test_err.txt # Standard error of the script
#SBATCH --time=0-48:00:00 # Limit on the total run time (format: days-hours:minutes:seconds)
#SBATCH --gres=gpu:v100:1 # Number of GPUs if needed
#SBATCH --cpus-per-task=12 # Number of CPUs (Don't use more than 24 per GPU)
#SBATCH --mem=100G # Memory in GB (Don't use more than 126G per GPU)

## activate corresponding environment
#source ~/miniconda3/etc/profile.d/conda.sh
#conda deactivate
#conda activate endovit

# run the program

# set outputs paths
OUTDIR="./finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT"
SEED=1665

for VIDEOS_TO_USE in "25 1" "33 11" "22 40" "8 28 13 4" "5 17 25 31" "24 28 38 15" "1 22 12 8 6 33 31 29" "20 38 25 7 29 4 2 24" "18 28 17 2 40 36 7 34"
do

video_count=$(echo ${VIDEOS_TO_USE} | wc -w)
video_str=$(echo ${VIDEOS_TO_USE} | tr " " "_")

DIR=${OUTDIR}/${video_count}_videos_only/videos_${video_str}
if [ ! -d ${DIR} ] ; then
	mkdir -p ${DIR}
fi

if [ ${video_count} -eq 2 ]; then
    MAX_EPOCHS=80
    MIN_EPOCHS=40
elif [ ${video_count} -eq 4 ]; then
    MAX_EPOCHS=60
    MIN_EPOCHS=20
else
    MAX_EPOCHS=40
    MIN_EPOCHS=10
fi

if [ "${VIDEOS_TO_USE}" = "25 1" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/2_videos_only/videos_25_1/21:04-07.11.24_TeCNO_2VidsOnly_EndoViT_Videos_25_1/checkpoints/21:04-07.11.24_TeCNO_2VidsOnly_EndoViT_Videos_25_1-epoch=10-val_acc=0.73.ckpt"
elif [ "${VIDEOS_TO_USE}" = "33 11" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/2_videos_only/videos_33_11/23:59-07.11.24_TeCNO_2VidsOnly_EndoViT_Videos_33_11/checkpoints/23:59-07.11.24_TeCNO_2VidsOnly_EndoViT_Videos_33_11-epoch=10-val_acc=0.65.ckpt"
elif [ "${VIDEOS_TO_USE}" = "22 40" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/2_videos_only/videos_22_40/02:57-08.11.24_TeCNO_2VidsOnly_EndoViT_Videos_22_40/checkpoints/02:57-08.11.24_TeCNO_2VidsOnly_EndoViT_Videos_22_40-epoch=13-val_acc=0.67.ckpt"
elif [ "${VIDEOS_TO_USE}" = "8 28 13 4" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/4_videos_only/videos_8_28_13_4/05:49-08.11.24_TeCNO_4VidsOnly_EndoViT_Videos_8_28_13_4/checkpoints/05:49-08.11.24_TeCNO_4VidsOnly_EndoViT_Videos_8_28_13_4-epoch=10-val_acc=0.71.ckpt"
elif [ "${VIDEOS_TO_USE}" = "5 17 25 31" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/4_videos_only/videos_5_17_25_31/08:47-08.11.24_TeCNO_4VidsOnly_EndoViT_Videos_5_17_25_31/checkpoints/08:47-08.11.24_TeCNO_4VidsOnly_EndoViT_Videos_5_17_25_31-epoch=10-val_acc=0.73.ckpt"
elif [ "${VIDEOS_TO_USE}" = "24 28 38 15" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/4_videos_only/videos_24_28_38_15/11:20-08.11.24_TeCNO_4VidsOnly_EndoViT_Videos_24_28_38_15/checkpoints/11:20-08.11.24_TeCNO_4VidsOnly_EndoViT_Videos_24_28_38_15-epoch=8-val_acc=0.62.ckpt"
elif [ "${VIDEOS_TO_USE}" = "1 22 12 8 6 33 31 29" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/8_videos_only/videos_1_22_12_8_6_33_31_29/14:10-08.11.24_TeCNO_8VidsOnly_EndoViT_Videos_1_22_12_8_6_33_31_29/checkpoints/14:10-08.11.24_TeCNO_8VidsOnly_EndoViT_Videos_1_22_12_8_6_33_31_29-epoch=12-val_acc=0.74.ckpt"
elif [ "${VIDEOS_TO_USE}" = "20 38 25 7 29 4 2 24" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/8_videos_only/videos_20_38_25_7_29_4_2_24/16:59-08.11.24_TeCNO_8VidsOnly_EndoViT_Videos_20_38_25_7_29_4_2_24/checkpoints/16:59-08.11.24_TeCNO_8VidsOnly_EndoViT_Videos_20_38_25_7_29_4_2_24-epoch=13-val_acc=0.81.ckpt"
elif [ "${VIDEOS_TO_USE}" = "18 28 17 2 40 36 7 34" ]; then
    TEST_CHECKPOINT="/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/finetuning_frozen_backbone/surgical_phase_recognition/output_dir/less_training_data/ViT_backbone/EndoViT/8_videos_only/videos_18_28_17_2_40_36_7_34/19:53-08.11.24_TeCNO_8VidsOnly_EndoViT_Videos_18_28_17_2_40_36_7_34/checkpoints/19:53-08.11.24_TeCNO_8VidsOnly_EndoViT_Videos_18_28_17_2_40_36_7_34-epoch=11-val_acc=0.73.ckpt"
fi

#python ./finetuning/surgical_phase_recognition/model/TeCNO/train.py \
#-c ./finetuning/surgical_phase_recognition/model/TeCNO/modules/mae/config/config_feature_extract_mae.yml \
#--mae_model "vit_base_patch16" \
#--mae_ckpt "/mnt/ceph/tco/TCO-Staff/Homes/kirchnema/04_pycharm/05_endovit_fl/03_EndoViT_FL_2/EndoViT_2/src/outputs/experiment_1C/Server/best_swa_model_server.pth" \
#--learning_rate 0.0005 \
#--freeze_weights -1 \
#--mae_layer_decay 0.65 \
#--mae_weight_decay 0. \
#--mae_reinit_n_layers -1 \
#--return_mae_optimizer_groups \
#--model_specific_batch_size_max 128 \
#--seed ${SEED} \
#--loss_balancing \
#--wandb_project_name "EndoViT_FedASAM_Finetuning_SurgicalPhaseRecognition" \
#--wandb_name_suffix "FullDataset_EndoViT_FedASAM_Seed_${SEED}" \
#--wandb_tags FeatureExtraction FullDataset EndoViT_FedASAM \
#--output_path ${DIR} 1> ${DIR}/fe_out.txt 2>${DIR}/fe_err.txt

python ./finetuning/surgical_phase_recognition/model/TeCNO/test.py \
-c ./finetuning/surgical_phase_recognition/model/TeCNO/modules/mstcn/config/config_tcn.yml \
--data_root ${DIR}/*FeatureExtraction*/cholec80_pickle_export \
--seed ${SEED} \
--wandb_project_name "EndoViT_finetuning_frozen_backbone_SurgicalPhaseRecognition" \
--wandb_name_suffix "${video_count}VidsOnly_EndoViT_FedASAM_Videos_${video_str}" \
--wandb_tags MSTCN ${video_count}VidsOnly ViT_backbone EndoViT_FedASAM \
--output_path ${DIR} 1> ${DIR}/test_tcn_out.txt 2>${DIR}/test_tcn_err.txt \
--resume_from_checkpoint ${TEST_CHECKPOINT}

done
